---
-- make/make_workspace.lua
-- Workspace makefile exporting.
--
-- Author Jason Perkins
-- Copyright (c) 2017 Jason Perkins and the Premake project
---

	local m = {}

	local p = premake

	m.elements = {}


---
-- Workspace export entry point.
---

	m.elements.workspace = function(wks)
		return {
			m.header,
			m.projectsVar,
			m.projectGroupsVar,
			m.phonyRule,
			m.allRule
		}
	end

	function m.export(wks)
		p.callArray(m.elements.workspace, wks)
	end


	function m.allRule(wks)
		p.w("all: $(PROJECTS)")
		p.w()
	end


	function m.header(wks)
		p.w("# GNU Make workspace makefile autogenerated by Premake")
		p.w()
	end


	function m.phonyRule(wks)
		p.w(".PHONY: all clean help $(PROJECTS) $(PROJECT_GROUPS)")
		p.w()
	end


	function m.projectGroupsVar(wks)
		p.w("PROJECT_GROUPS :=")
		p.w()
	end


	function m.projectsVar(wks)
		p.w("PROJECTS :=")
		p.w()
	end


---
-- End of module
---

	return m
