---
-- make/make_project.lua
-- Project makefile exporting.
--
-- Author Jason Perkins
-- Copyright (c) 2017 Jason Perkins and the Premake project
---

	local m = {}

	local p = premake

	m.elements = {}


---
-- Project export entry point.
---

	m.elements.project = function(wks)
		return {
			m.header
		}
	end

	function m.export(prj)
		p.callArray(m.elements.project, prj)
	end


	function m.header()
		p.w("# GNU Make project makefile autogenerated by Premake")
	end


---
-- End of module
---

	return m
