---
-- make/tests/project/test_header.lua
-- Verify project header comment blocks.
--
-- Author Jason Perkins
-- Copyright (c) 2017 Jason Perkins and the Premake project
---

	local suite = test.declare("make_project_header")

	local p = premake

	local m = require("make")


---
-- Construct a new Query instance from an existing Context.
---

	function suite.looksOkay_onDefaultSetup()
		m.project.header()
		test.capture [[
# GNU Make project makefile autogenerated by Premake
		]]
	end
